#!/usr/bin/env bash
# script displays subdomain information

details() {
	dig "$2.$1" | awk '/;; ANSWER SECTION/ {getline;
	printf "The subdomain %s is a %s record and points to %s\n", S_D, $3, $5}' S_D="$2"
}

if [ $# -gt 1 ]
then
	details "$1" "$2"
else
	details "$1" "www"
	details "$1" "lb-01"
	details "$1" "web-01"
	details "$1" "web-02"
fi
