#!/usr/bin/env bash
# Intsalls NGINX web server on web-01 server

# installs NGINX
apt-get update
apt-get -y install nginx
sed -i '24 i \\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4i permanent;' /etc/nginx/sites-enabled/default
service nginx restart
