#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

apt-get update
apt-get -y install nginx
touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '25 i \\terror_page 404 = /404.html;' /etc/nginx/sites-enabled/default
service nginx restart
