#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
apt-get -y update
apt install -y haproxy
sudo sed -i "$ aENABLED=1" /etc/init.d/haproxy
echo "
frontend load_balancer
    bind *:80
    mode http
    default_backend webserver
backend webserver
    balance roundrobin
    server 3240-web-01 34.139.237.184:80 check
    server 3240-web-02 3.80.64.94:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
