#!/usr/bin/env bash
# script installs apache and runs it in the docker container
apt-get update
apt-get -y install apache2
echo "ServerName localhost" >> /etc/apache2/conf-available/servername.conf
service apache2 restart
