#!/usr/bin/env bash
# Fixes container so that Nginx is running as the nginx user
sudo sed -i "s/#user www-data;/user nginx;/g" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo pkill apache2
sudo -u nginx service nginx start
